FROM ubuntu:jammy

EXPOSE 5000

ENV ASPNETCORE_ENVIRONMENT="Production"
ENV ASPNETCORE_URLS="http://*:5000"

RUN \
  apt-get -y update && \
  apt-get -y install \
  apt-utils \
  wget \
  apt-transport-https \
  unzip \
  acl \
  libssl1.0

RUN \
  apt-get -y install aspnetcore-runtime-6.0

RUN \
  adduser --disabled-password --gecos '' -u 2001 nexremote && \
  mkdir -p /var/www/nex-remote && \
  mkdir /config && \
  wget -q https://github.com/nexitpl/nex-Remote/releases/latest/download/nex-Remote_Server_Linux-x64.zip && \
  unzip -o nex-Remote_Server_Linux-x64.zip -d /var/www/nex-Remote && \
  rm nex-Remote_Server_Linux-x64.zip && \
  chown -R nexremote:nexremote /var/www/nex-Remote

RUN \
  mkdir -p /nexremote-data && \
  sed -i 's/DataSource=nex-Remote.db/DataSource=\/nexremote-data\/nex-Remote.db/' /var/www/nex-Remote/appsettings.json && \
  chown -R nexremote:nexremote /nexremote-data

VOLUME "/nexremote-data"

WORKDIR /var/www/nex-Remote

COPY DockerMain.sh /

RUN chmod 755 /DockerMain.sh

USER nexremote

ENTRYPOINT ["/DockerMain.sh"]
