FROM ubuntu:jammy

EXPOSE 5000

ENV ASPNETCORE_ENVIRONMENT="Production"
ENV ASPNETCORE_URLS="http://*:5000"

RUN \
  apt-get -y update && \
  apt-get -y install \
  apt-utils \
  wget \
  apt-transport-https \
  unzip \
  acl \
  libssl1.0

RUN \
  apt-get -y install aspnetcore-runtime-6.0

RUN \
  adduser --disabled-password --gecos '' -u 2001 nexremote && \
  mkdir -p /var/www/nexRemote && \
  mkdir /config && \
  wget -q https://github.com/nexitpl/nexRemote/releases/latest/download/nexRemote_Server_Linux-x64.zip && \
  unzip -o nexRemote_Server_Linux-x64.zip -d /var/www/nexRemote && \
  rm nexRemote_Server_Linux-x64.zip && \
  chown -R nexremote:nexremote /var/www/nexRemote

RUN \
  mkdir -p /nexremote-data && \
  sed -i 's/DataSource=nexRemote.db/DataSource=\/nexremote-data\/nexRemote.db/' /var/www/nexRemote/appsettings.json && \
  chown -R nexremote:nexremote /nexremote-data

VOLUME "/nexremote-data"

WORKDIR /var/www/nexRemote

COPY DockerMain.sh /

RUN chmod 755 /DockerMain.sh

USER nexremote

ENTRYPOINT ["/DockerMain.sh"]
